# An if block is used for decision making in Python.
# It checks a condition, and if the condition is TRUE, it executes the code inside the block.

age1 = 18
if age1 >= 18:
    print("You are eligible to vote")


# An if-else block is used when you want two choices:
# If condition is True → run if block
 # If condition is False → run else block


# if condition:
#     # code if true
#     else:
#     # code if false

age = 16
if age >= 18:
    print("You can vote")
else:
    print("You cannot vote")